// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantoEuCobro.Infrastructure;

#nullable disable

namespace QuantoEuCubro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507195922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.CampoPersonalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropostaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoCampo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId");

                    b.ToTable("CamposPersonalizados");
                });

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.Proposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeVisualizacoes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaVisualizacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PublicToken")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Propostas");
                });

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorPrimaria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorSecundaria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlBase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Premium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Tecnologia",
                            CorPrimaria = "#6C63FF",
                            CorSecundaria = "#F3F4F6",
                            Fonte = "Poppins",
                            Nome = "Moderno",
                            Premium = false,
                            Thumbnail = "/thumbnails/moderno.png"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Design",
                            CorPrimaria = "#1A1A2E",
                            CorSecundaria = "#E8C547",
                            Fonte = "Playfair Display",
                            Nome = "Elegante",
                            Premium = false,
                            Thumbnail = "/thumbnails/elegante.png"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Agência",
                            CorPrimaria = "#0F172A",
                            CorSecundaria = "#38BDF8",
                            Fonte = "Montserrat",
                            Nome = "Premium Pro",
                            Premium = true,
                            Thumbnail = "/thumbnails/premium.png"
                        });
                });

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.CampoPersonalizado", b =>
                {
                    b.HasOne("QuantoEuCobro.Domain.Entities.Proposta", "Proposta")
                        .WithMany("Campos")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.Proposta", b =>
                {
                    b.HasOne("QuantoEuCobro.Domain.Entities.Template", "Template")
                        .WithMany("Propostas")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuantoEuCobro.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Propostas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.Proposta", b =>
                {
                    b.Navigation("Campos");
                });

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.Template", b =>
                {
                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("QuantoEuCobro.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Propostas");
                });
#pragma warning restore 612, 618
        }
    }
}
